#!/bin/sh

#	This script doesn't use official api so it's a bit limited
#	it can only return an image with the graphs (the same that you get on meteo.pl)
#	
#	It's meant for weather in Poland,
#	but they offer a few capital cities in neighbouring countries


defaultcity="warszawa" # you will get this with no arguments
lang="lang=pl" # pl or en

# substitute this with appropriate command for your DE / WM
# or leave as is
openimage="xdg-open"

# this script will create files inside this path
# it wont work if the initial path doesn't exist
# change it to whatever you like
path="$(printenv HOME)/Downloads"

if [ "${#}" = '0'  ]; then
	city="${defaultcity}"
elif [ "${1}" = "-h" ]; then
	echo -e ""
	echo -e "\tmeteo-pl [city]"
	echo -e ""
	echo -e "\t\tIf the city is not specified"
	echo -e "\t\tit will use default one (look inside the script)"
	echo -e ""
	echo -e "\tAvilable cities in Poland:"
	echo -e "\t\tbialystok	bydgoszcz	gdansk"
	echo -e "\t\tgorzow		katowice	kielce"
	echo -e "\t\tkarow		lublin		lodz"
	echo -e "\t\tolsztyn		opole		poznan"
	echo -e "\t\trzeszow		szczecin	torun"
	echo -e "\t\twarszawa	wroclaw		zielonagora"
	exit 1
else
	city="$1"
fi

case $city in
	"bialystok")	row=379 && col=285;;
	"bydgoszcz")	row=381 && col=199;;
	"gdansk")		row=346 && col=210;;
	"gorzow")		row=390 && col=152;;
	"katowice")		row=461 && col=215;;
	"kielce")		row=443 && col=244;;
	"krakow")		row=466 && col=232;;
	"lublin")		row=432 && col=277;;
	"lodz")			row=418 && col=223;;
	"olsztyn")		row=363 && col=240;;
	"opole")		row=449 && col=196;;
	"poznan")		row=400 && col=180;;
	"rzeszow")		row=465 && col=269;;
	"szczecin")		row=370 && col=142;;
	"torun")		row=383 && col=209;;
	"warszawa")		row=406 && col=250;;
	"wroclaw")		row=436 && col=181;;
	"zielonagora")	row=412 && col=155;;
	*) 				echo "Wrong city name!" && exit 1;;
esac

now="$(date +'%Y-%m-%d-%H')"
row="row=${row}"
col="col=${col}"

url="https://www.meteo.pl/um/metco/mgram_pict.php?ntype=0u&${row}&${col}&${lang}"

# save path creation
pathend=${#path}-1
if [ "${path:pathend}" != '/' ]; then
	path="${path}/"
fi
path="${path}${city}-${now}.png"

wget -O ${path} ${url}

$(${openimage} ${path})