#!/bin/sh

#	Get current weather from meteo.pl for Warsaw

now="$(date +'%Y%m%d%H')"
url="https://www.meteo.pl/um/metco/mgram_pict.php?ntype=0u&row=406&col=250&lang=pl"
path="$(printenv HOME)/Documents/weather/wwa/${now}.png"

wget -O ${path} ${url}

xdg-open ${path}